apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app:
      server
  ports:
  - protocal: TCP
    port: 80 
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/vi
kind: Deployment
metadata: 
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: server
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: animal-noises-server
        image: jcarr172/animail_noises_server:latest
        ports:
        - containerPorts: 5000